(env) slurm luna-01:357098> python3 Unetmultiinput1/unet.py --device cuda --mode predict --model_path Unetmultiinput1/results/checkpoints/model_epoch_3.pth --output_dir Unetmultiinput1/results/predictions
Predicting:   0%|                                                           | 0/15 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/rnga/dawezenberg/my-rdisk/r-divi/RNG/Projects/stages/Pim/Doris/BBDM_Thesis/Unetmultiinput1/unet.py", line 234, in <module>
    predict_and_save(model, test_loader, args.model_path, args.output_dir)
  File "/home/rnga/dawezenberg/my-rdisk/r-divi/RNG/Projects/stages/Pim/Doris/BBDM_Thesis/Unetmultiinput1/unet.py", line 212, in predict_and_save
    for i, (inputs, _) in enumerate(tqdm(loader, desc='Predicting')):
ValueError: too many values to unpack (expected 2)